// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ7pSlafMcPSEBFLy4D7P6DBOSk8-qY6Q',
    appId: '1:920465515367:web:aa697e78b501aaa94a45c2',
    messagingSenderId: '920465515367',
    projectId: 'flutter-my-app-70068',
    authDomain: 'flutter-my-app-70068.firebaseapp.com',
    storageBucket: 'flutter-my-app-70068.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLXoULjn--DIGGfGd0LCogJTbPY9SirMM',
    appId: '1:920465515367:android:09874154d9df872b4a45c2',
    messagingSenderId: '920465515367',
    projectId: 'flutter-my-app-70068',
    storageBucket: 'flutter-my-app-70068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbqq7-VsCRvnOr3Ns6n93TZFXnvN8m2lo',
    appId: '1:920465515367:ios:32c9bbc1c1fb59a24a45c2',
    messagingSenderId: '920465515367',
    projectId: 'flutter-my-app-70068',
    storageBucket: 'flutter-my-app-70068.appspot.com',
    iosClientId: '920465515367-kqka6o201v63hdtj211nvn82b892m38r.apps.googleusercontent.com',
    iosBundleId: 'com.elquineas.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbqq7-VsCRvnOr3Ns6n93TZFXnvN8m2lo',
    appId: '1:920465515367:ios:b00364152896928b4a45c2',
    messagingSenderId: '920465515367',
    projectId: 'flutter-my-app-70068',
    storageBucket: 'flutter-my-app-70068.appspot.com',
    iosClientId: '920465515367-jhd2coboo1917l7sdft0pu9gr55489cq.apps.googleusercontent.com',
    iosBundleId: 'com.elquineas.firebase.RunnerTests',
  );
}
